// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }

// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import Link from "next/link";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        
//         {/* Navbar */}
//         <nav className="bg-gradient-to-br from-[#34e89e] to-[#0f3443] text-white p-4 shadow-lg">
//           <div className="max-w-7xl mx-auto flex justify-between items-center">
//             <Link href="/" className="text-2xl font-bold">MentalHealthDApp</Link>
//             <div className="space-x-6">
//               <Link href="/" className="hover:text-gray-300">Home</Link>
//               <Link href="/dashboard/therapist" className="hover:text-gray-300">Therapist Dashboard</Link>
//               <Link href="/dashboard/user" className="hover:text-gray-300">User Dashboard</Link>
//               <Link href="/about" className="hover:text-gray-300">About</Link>
//             </div>
//           </div>
//         </nav>

//         {/* Main content */}
//         {children}
//       </body>
//     </html>
//   );
// }


// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import Link from "next/link";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        
//         {/* Navbar */}
//         <nav className="bg-gradient-to-br from-[#34e89e] to-[#0f3443] text-white p-4 shadow-lg">
//           <div className="max-w-7xl mx-auto flex justify-between items-center">
//             {/* Logo Section */}
//             <Link href="/" className="flex items-center space-x-2">
//               {/* Replace '/public/logo.png' with your actual logo path */}
//               <img src="/logo.png" alt="Website Logo" className="h-10" /> 
//               <span className="text-2xl font-bold">SoulChain</span>
//             </Link>

//             {/* Navbar Links */}
//             <div className="space-x-6">
//               <Link href="/logo.jpeg" className="hover:text-gray-300">Home</Link>
             
//               <Link href="/dashboard/therapist" className="hover:text-gray-300">Therapist Dashboard</Link>
//               <Link href="/dashboard/user" className="hover:text-gray-300">User Dashboard</Link>
//               {/* <Link href="/about" className="hover:text-gray-300">About</Link> */}
//               <Link href="/contact" className="hover:text-gray-300">Contact Us</Link>
//               <Link href="/login" className="hover:text-gray-300"> Login</Link>

//             </div>
//           </div>
//         </nav>

//         {/* Main content */}
//         {children}
//       </body>
//     </html>
//   );
// }


import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Soulchain",
  description: "soulchain",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* Navbar */}
        <nav className="bg-gradient-to-br from-[#34e89e] to-[#0f3443] text-white p-6 shadow-lg">
          <div className="max-w-7xl mx-auto flex justify-between items-center">
            {/* Logo Section */}
            <Link href="/" className="flex items-center space-x-2">
              <img src="/logo.png" alt="Website Logo" className="h-12 transition-transform duration-300 hover:scale-110" /> {/* Added hover effect */}
              <span className="text-3xl font-extrabold text-gray-100">SoulChain</span> {/* Enhanced logo font size */}
            </Link>

            {/* Navbar Links */}
            <div className="space-x-6 hidden md:flex">
              <Link href="/" className="hover:text-gray-300 transition duration-300">Home</Link>
              <Link href="/dashboard/therapist" className="hover:text-gray-300 transition duration-300">Therapist Dashboard</Link>
              <Link href="/dashboard/user" className="hover:text-gray-300 transition duration-300">User Dashboard</Link>
              <Link href="/contact" className="hover:text-gray-300 transition duration-300">Contact Us</Link>
              <Link href="/login" className="hover:text-gray-300 transition duration-300">Login</Link>
            </div>

            {/* Mobile Menu Toggle (Hamburger) */}
            <div className="md:hidden">
              <button className="text-3xl">☰</button> {/* Simple hamburger icon */}
            </div>
          </div>
        </nav>

        {/* Main content */}
        {children}
      </body>
    </html>
  );
}
